# The name of your site inside Pages CMS
site: "My Site"

# Where uploaded media should be stored in your repo
media:
  input: "static/uploads"
  output: "/uploads"

# Define content collections the CMS can edit
content:
  # Sharable content snippets that can be imported into markdown files
  - name: "snippets"
    label: "Content Snippets"
    type: collection
    path: "content/snippets"
    fields:
      - name: "name"
        label: "Snippet Name"
        type: string
        required: true
      - name: "slug"
        label: "Slug"
        type: string
        required: true
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      - name: "content"
        label: "Content"
        type: rich-text
        required: true
      - name: "description"
        label: "Description"
        type: text
      - name: "tags"
        label: "Tags"
        type: list

  # Example for static pages (About, Contact, etc.)
  - name: "pages"
    label: "Site Pages"
    type: collection
    path: "content/pages"
    fields:
      - name: "title"
        label: "Title"
        type: string
        required: true
      - name: "image"
        label: "Image"
        type: image
      - name: "video"
        label: "Video"
        type: file
      - name: "body"
        label: "Body"
        type: rich-text
      - name: "intro"
        label: "Intro Snippet"
        type: reference
        options:
          collection: snippets
      - name: "outro"
        label: "Outro Snippet"
        type: reference
        options:
          collection: snippets
